config/routes.rb
Rails.application.routes.draw do
  resources :transactions

  resources :accounts

  devise_for :users

  #get 'users/auth/facebook/callback' => 'authentications#facebook_callback'

  resources :certs

  resources :stores

  #debug
  get 'facebook_js', :to => 'certs#facebook_js'


  get 'facebook_auth/callback', :to => 'authentications#facebook_auth_callback'

  root :to => 'certs#new'
end

app/models/cert.rb
class Cert < ActiveRecord::Base
  include CertsHelper
  SOURCES = %w|facebook twitter email|

  validates :amount, :presence => true, :numericality => {:greater_than => 0}

  belongs_to :receiver, :class_name => 'User'
  belongs_to :giver, :class_name => 'User'

  belongs_to :account

  validates :giver_source, :inclusion => {:in => SOURCES, :allow_nil => true}
  validates :receiver_source, :inclusion => {:in => SOURCES, :allow_nil => true}

  validate :giver_is_identifiable, :receiver_is_identifiable, :amount_is_greater_than_store_minimum,
           :user_is_known_before_credited
  private
    def user_is_known_before_credited
      errors.add(:user, 'cannot be blank') if credited && receiver_id.nil?
    end

    def giver_is_identifiable
      if giver_id.nil?
        errors.add(:giver_source, 'cannot be blank') if giver_source.blank?
        errors.add(:giver_identifier, 'cannot be blank') if giver_identifier.blank?
      end
    end

  def receiver_is_identifiable
    if receiver_id.nil?
      errors.add(:receiver_source, 'cannot be blank') if receiver_source.blank?
      errors.add(:receiver_identifier, 'cannot be blank') if receiver_identifier.blank?
    end
  end

  def amount_is_greater_than_store_minimum
    if cert_store
      errors.add(:amount, "must be more than the minimum of #{cert_store.minimum_certificate_amount}") if amount < cert_store.minimum_certificate_amount
    end
  end
  public

  #Methods
  def credit
    raise(StandardError, 'cannot credit without an account') if account_id.nil?
    account << amount
    self.credited = true
    save
  end


end

app/controllers/certs_controller.rb
class CertsController < ApplicationController
  before_action :set_cert, only: [:show, :edit, :update, :destroy]

  def facebook_js

  end

  # GET /certs
  def index
    @certs = Cert.all
  end

  # GET /certs/1
  def show
  end

  # GET /certs/new
  def new
    @cert = Cert.new
  end

  # GET /certs/1/edit
  def edit
  end

  # POST /certs
  def create
    @cert = Cert.new(cert_params)

    if @cert.save
      redirect_to @cert, notice: 'Cert was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /certs/1
  def update
    if @cert.update(cert_params)
      redirect_to @cert, notice: 'Cert was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /certs/1
  def destroy
    @cert.destroy
    redirect_to certs_url, notice: 'Cert was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cert
      @cert = Cert.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cert_params
      params.require(:cert).permit(:user_id, :amount, :giver_id, :note, :giver_identifier)
    end
end

app/helpers/certs_helper.rb
module CertsHelper
  #include FacebookHelper
  include ErrorsHelper
  include HtmlTools

  def cert_store
    Store.first
  end

  def store_name
    cert_store ? cert_store.name : '[Your Store Here]'
  end

  def current_user_is_admin?
    user_signed_in? || current_user.admin?
  end

  #for Devise
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/certs/_form.html.erb
<style>
  .cert_col{
      height: 300px;
      /*background-color: rgba(169, 169, 169, 0.27);*/
      color: rgba(14, 2, 12, 0.80);
  }
  .cert_col h2{
      vertical-align: middle;
  }

  .cert_col .inner_col{
      padding: 10px;
      border: 1px solid red;
      height: 300px;
  }
  .blocker_col{
      position: relative;
      /*top: -10%;*/
      /*left: -100%;*/
      color: rgba(0, 0, 0, 0.51);
      height: 300px;
  }
</style>


<%= form_for(@cert) do |f| %>
 <%= error_explanation @cert, :include_text_explanation => false %>



 <div class="row">
   <div id="giver_col" class="col-md-4 cert_col">
     <div class="inner_col">
       <h2>From:</h2>

       <% if user_signed_in? %>



       <% else %>

         <div class="form-group">
           <%= link_to image_tag('social_networking_buttons/fb_sign_in.png'), '#', :class => 'custom_button facebook_sign_in' %>
         </div>

       <% end %>


       <div class="blocker_col">

       </div>
     </div><!--inner col-->
   </div><!--col-->

   <div id="receiver_col" class="col-md-4 cert_col">
     <div class="inner_col">
       <h2>
         Please login to select a Recipient.<br>
         <small>You can send our gift certificates via:
           <ul id="giving_options">
             <%= to_li(GIVING_OPTIONS) %>
           </ul>
         </small>
       </h2>
     </div><!--inner col-->
   </div><!--col-->

   <div id="amount_col" class="col-md-4 cert_col">
   </div><!--col-->

   </div><!--col-->
 </div>
<% end %>

app/views/certs/edit.html.erb
<h1>Editing cert</h1>

<%= render 'form' %>

<%= link_to 'Show', @cert %> |
<%= link_to 'Back', certs_path %>

app/views/certs/facebook_js.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <style>

  </style>
  <meta charset="utf-8">
  <title>Facebook Sandbox</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
</head>
<body>
<a href="#" class="facebook_login">Click me</a>



<script>
    $(document).ready(function(){
        $('body').prepend('<div id="facebook-root"></div>');

        (function(d, s, id){
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {return;}
            js = d.createElement(s); js.id = id;
            js.src = "http://connect.facebook.net/en_US/all.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    });
    window.fbAsyncInit = function(){
        FB.init({
            appId: '<%= FB_ID %>',
            cookie: true,
            xfbml: true
        });
    };
    $(document).on('click', '.facebook_login', function(e){
        e.preventDefault();
        fbLogin();
    });
    function fbLogin(permissions){
        FB.login(function(response){
            if(response.authResponse){
                $.ajax({
                    url: 'facebook_auth/callback'
                });
            }
        }, {scope: permissions});
    };
</script>

<script>
    $(document).on('click', '.click', function(e){
        FB.api('/me', function(r){
            console.log(r);
        });
    })
</script>


</body>
</html>

app/views/certs/index.html.erb
<h1>Listing certs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Amount</th>
      <th>Giver</th>
      <th>Note</th>
      <th>Giver identifier</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @certs.each do |cert| %>
      <tr>
        <td><%= cert.user_id %></td>
        <td><%= cert.amount %></td>
        <td><%= cert.giver_id %></td>
        <td><%= cert.note %></td>
        <td><%= cert.giver_identifier %></td>
        <td><%= link_to 'Show', cert %></td>
        <td><%= link_to 'Edit', edit_cert_path(cert) %></td>
        <td><%= link_to 'Destroy', cert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cert', new_cert_path %>

app/views/certs/new.html.erb
<div class="container main_container">
  <h1 class="text-center">Give a Gift from <%= store_name %></h1>
  <h2><%= FB_ID %></h2>
  <%= render 'form' %>
</div>

app/views/certs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cert.user_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @cert.amount %>
</p>

<p>
  <strong>Giver:</strong>
  <%= @cert.giver_id %>
</p>

<p>
  <strong>Note:</strong>
  <%= @cert.note %>
</p>

<p>
  <strong>Giver identifier:</strong>
  <%= @cert.giver_identifier %>
</p>

<%= link_to 'Edit', edit_cert_path(@cert) %> |
<%= link_to 'Back', certs_path %>